### ISSUE TITLE
 Korlan USB2CAN OBD2 status

### ISSUE THREAD

**Issue by rusefillc** [moonglow/pcan_cantact#11]
do we know if Korlan USB2CAN OBD2 would run official binaries?

**Comment by rusefillc** [comment]
Does pcan_cantact have "software switch to DFU" command in the protocol?

here's the problem with those nice-looking Korlan USB2CAN OBD2 devices: those do not have HW DFU switch. you invoke magic Korlan command to switch it to DFU mode.

So if it accepts pcan_cantact FW how does one switch it back to Korlan if desired? :) 

Worse if pcan_cantact  does not start :)

![image](https://user-images.githubusercontent.com/48498823/144961257-c24907a7-4644-4b91-8393-ecb46d87ad70.png)

**Comment by moonglow** [comment]
>do we know if Korlan USB2CAN OBD2 would run official binaries?

I think you can try it, first of all you need to build pin map first to make sure that it has no conflict with existing ones ( used in my firmware ) , next you can flash firmware and all be OK i think

>Does pcan_cantact have "software switch to DFU" command in the protocol?

Nope, because STM32F042 ( which firmware was designed for ) does not support USB DFU, but STM32F072 does, another thing their firmware started by their own internal bootloader with DFU commands set support ( that's why base address of Korlan firmware is 0x8008000 ) and looks like USB2CAN-v2.0.bin was encrypted. If MCU is not locked you can read full flash first to make sure that you can revert back.

**Comment by rusefillc** [comment]
The original device is read out protected.

The is BOOT0 on the back pad.

middle LED looks to be PD2
further away LED looks to be PC12
