### ISSUE TITLE
question about pcan usb protocol

### ISSUE THREAD

**Issue by andywang1005** [moonglow/pcan_cantact#19]
hello, Moonglow

Do you have some documents about PCAN protocol introduction? it's difficult for me to understand the "pcan protocol.c".
Thanks you very much!

Best Regards!

**Comment by moonglow** [comment]
Hi @andywang1005  !

PEAK do not provides any protocol description in any kind. So i just use their [open source Linux drivers](https://www.peak-system.com/fileadmin/media/linux/index.htm) and got all info from them. I also wants to notice, what PEAK company does not like my project and that's why i was made ( by their notice ) changes to VID/PID pair and also stops my development for that projects. Their also tries to block my firmware with their new drivers updates. So you can only analyze my sources or their linux sources and write your own protocol description.

**Comment by kristyandi** [comment]
> Hi @andywang1005 !
> 
> PEAK do not provides any protocol description in any kind. So i just use their [open source Linux drivers](https://www.peak-system.com/fileadmin/media/linux/index.htm) and got all info from them. I also wants to notice, what PEAK company does not like my project and that's why i was made ( by their notice ) changes to VID/PID pair and also stops my development for that projects. Their also tries to block my firmware with their new drivers updates. So you can only analyze my sources or their linux sources and write your own protocol description.
ps: is vector fw having similar open source Linux drivers to analyze.

**Comment by moonglow** [comment]
@kristyandi 

> ps: is vector fw having similar open source Linux drivers to analyze.

Nope, Vector supports only Windows OS and has no open source solution  :(

**Comment by P208PUG** [comment]
> @kristyandi
> 
> > ps: is vector fw having similar open source Linux drivers to analyze.
> 
> Nope, Vector supports only Windows OS and has no open source solution :(

can you reopen the vector_can git?

**Comment by moonglow** [comment]
@P208PUG

You can try now
